<center><img src="../images/Logo_200x280.png"></center>
<p>This project of  <b>ForestCoin.Space</b> operated by <b>The Legal Assistance Foundation.</b></p>

<p><center><img src="../images/Logo_Foundation_InstantPrint_TwoTone_192x200.png"></center>
</p>

<p>
<center><b>ABOUT THE FOUNDATION</b></center>
</p>
<p>
The Legal Assistance Foundation has registered at Bangkok City Hall, Thailand on June 15, 1995. with variety of volunteers join together. With the initial objective to assist the public regarding legal issues, to promote public benefit activities and environment protection. The situation of global warming mainly caused by deforestation become a big problem of the world. The foundation’s workgroup composed of university professors, former military and police officers, academic and social workers, and also business owners, have been following this issue for long time. Forest destruction damage the environment and cause the natural disasters. Despite, the credible academic report of the government mentioned about Thailand’s forest
area remain only 32%, out of 60% in
the previous 50 years. The Thai and
people from all over the world have
to pay close attention to this matter.
The project also intend to promotes
replanting and supports the way of
living in comply with the sustainable
nature and conservation guidelines
based on Sufficiency Economy Philosophy (SEP) of King Rama IX. The working group has initially agreed to use 2,200 plots of land as mentioned. This is a model project with many organizations involved, such as Bangkok Cryp Co., Ltd., Eam Thip Rice Co., Ltd., Siam Advisory Co., Ltd. , Eastern Cyber Co., Ltd., and Sinsub Agricultural 9999 Co., Ltd. as well as bloggers, financial experts, lawyers and former high-ranking officials, join together. Moreover, Chunlaporn Nantapanich, a famous architect who specializes in natural and environmental friendly building is part of the project, responsible for the utilization of overall landscape, buildings and facilities design on behalf of Northforest Studio Co., Ltd.
</p>


<p><center>
<b><a href="https://drive.google.com/file/d/1qYGz3-9-bWGmSdwdZ7q_P33Nh75Qgv1W/view?usp=sharing">WHITEPAPER</a></b>
</center>
</p>

<p>Chat with our team :</p>
<p><center><script src="https://apps.elfsight.com/p/platform.js" defer></script></p>
<div class="elfsight-app-5ab46d6d-5117-40d0-801e-55a5b08494a6"></div>
<p></center></p>

<p><center>
<script async type="text/javascript" src="https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/40313ca567a5a000ecd55f42c640e15badf56168fa550522704f1efcd736f764.js"></script>
</center></p>
