<center><a href="https://drive.google.com/file/d/1qYGz3-9-bWGmSdwdZ7q_P33Nh75Qgv1W/view?usp=sharing"><img src="../images/Logo_200x280.png"></a>
<p>
<b>The Sustainable Forest Park  and Crowd Planting Application</b>
</p>
<p> 
Conservation & Reforestation Project and Application <br> for <br> world wide tree planting against global warming.
</p>
</center>
</p>
<p>
<b>ABSTRACT</b><br>
The new dimension of blending
“Blockchain Technology” to represent the rights of creating guidelines and management policies for the forest and natural resources in conservation perspective. Including to support the balanced lifestyle of sustainable living in harmony with nature. The reason of this story is from what we previously believed that, conservation project need to be funded without financial profit. But, in this era of blockchain and cryptocurrency, the priceless value of natural resources could reflect the value of digital coin. Which will make the conservation project more profitable than the pursuit of benefits from natural resources with regardless of the environmental degradation.
</p>
<p>
The Foundation is your representative. To work for the public benefit. You can participate in the showcase of power and set policies and guidelines. It is a new form of charitable public organization. To be transparent and truly represent the public organization via “Blockchain Technology”.
</p>
<p>
You may be shocked, if you expect in ROI of 50-60%, which is very high compared to any general business investment, or even in the most wonderful stock exchange. But, what has happen to Bitcoin and other major digital coins, in the past 3 - 8 years, has been unbelievable growth of value. It has not just a 100 % of growth, but it’s soared up like 10,000 - 100,000 times or more. That means much more than millions % of growth. This has never happened to anything before, on this planet earth.
Our project, Sustainable Forest Park and the ForestCoin initiative, are part of this phenomenon. Unlike any other conservation projects, our ingenious ecosystem will gradually add the value to the nature in the selected prototype forest area, then successively expand to the rest of the world. These will reflect the fabulous value to the coin. We have also set the strategy to induce the coin holder to keep ForestCoin in long term. Moreover, every stage of project development will be publicized periodically and continuously. This will help to significantly push up the value of ForestCoins on exchange markets. This is what we call the limitless “Growth on Progress” or GoP. 
</p>

<p><center>
<b><a href="https://drive.google.com/file/d/1qYGz3-9-bWGmSdwdZ7q_P33Nh75Qgv1W/view?usp=sharing">WHITEPAPER</a></b>
</center>
</p>
