<center><img src="../images/Logo_200x280.png">
<p><b>BLOCKCHAIN TECHNOLOGY</b></p>
</center>
<p>
<b>“Blockchain”</b> the technology which could revolutionize the world in many dimensions. Most of the people know about blockchain from the advent of Bitcoin (BTC) during the year 2009 then become the digital currency which is accepted throughout the world. The form of digital currency is only a small part of Blockchain. In fact, the Blockchain Technology can be applied to every valuable thing in this whole world.</p>
<p>
<b>ForestCoin’s project,</b> have adopted Blockchain to represent the rights of creating guidelines and management policies for forest park and degraded forest area in conservation perspective. The “Sustainable Forest Park” Project have launched the digital currency named ForestCoin, then give to the contributors who join the support. The value of ForestCoin will be matched to the value of conservative forest area under the project, initially on the first phase of 2,200 rai (around 869 acre) in Maechan District, the northern province of Chiang Rai, Thailand.</p>
<p>
This is the new dimension of Digital Coin which is backed by the actual valuable property. More over, ForestCoin could be applied with many other activities under this project. If this initial concept could be succeeded, there will be the other follower phase which could continuously boost up the value of ForestCoin. Which could say that, the contributors to this public benefit project, could be proud of their contribution and get a chance to make profit from the value of ForestCoin which may increase in the future.</p>

<p><center>
<b><a href="https://drive.google.com/file/d/1qYGz3-9-bWGmSdwdZ7q_P33Nh75Qgv1W/view?usp=sharing">WHITEPAPER</a></b>
</center>
</p>
